"""
LTGG Trade Performance Dashboard
Reads pre-processed data from data.pkl (generated by build_data_pkl.py / the Colab notebook).
"""

from __future__ import annotations

import pickle
from datetime import date, datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# -------------------------------------------------------------------
# Page config
# -------------------------------------------------------------------
st.set_page_config(
    page_title="LTGG Trade Performance",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
)

PKL_PATH = "data.pkl"

# -------------------------------------------------------------------
# Data loading (cached, auto-invalidates when the pickle file changes)
# -------------------------------------------------------------------
@st.cache_data(show_spinner="Loading data…")
def load_data(pkl_path: str = PKL_PATH, _mtime: float | None = None):
    """`_mtime` is part of the cache key, so the cache is invalidated
    automatically whenever data.pkl is replaced."""
    with open(pkl_path, "rb") as f:
        return pickle.load(f)


def _pkl_mtime(pkl_path: str = PKL_PATH) -> float:
    p = Path(pkl_path)
    return p.stat().st_mtime if p.exists() else 0.0


if not Path(PKL_PATH).exists():
    st.error(
        f"`{PKL_PATH}` not found. Generate it with **build_data_pkl.py** "
        "(or run **build_data_pkl.ipynb** in Colab) and place it next to `app.py`."
    )
    st.stop()

data = load_data(PKL_PATH, _mtime=_pkl_mtime(PKL_PATH))
trades: pd.DataFrame = data["trades"]
prices: pd.DataFrame = data["prices"]

# -------------------------------------------------------------------
# Helpers
# -------------------------------------------------------------------
def price_on_or_after(series: pd.Series, dt: pd.Timestamp):
    s = series.dropna()
    v = s[s.index >= dt]
    return float(v.iloc[0]) if len(v) else None


def price_on_or_before(series: pd.Series, dt: pd.Timestamp):
    s = series.dropna()
    v = s[s.index <= dt]
    return float(v.iloc[-1]) if len(v) else None


BUY_TYPES = {"New Buy", "Addition"}


def compute_performance(df: pd.DataFrame, full_trades: pd.DataFrame,
                        prices: pd.DataFrame, mode: str,
                        end_date: pd.Timestamp | None, fixed_days: int | None):
    """For each trade in `df`, compute % return between the trade date and an
    appropriate end date. For New Buy / Addition trades whose position was
    later completely sold, the end date is capped at that subsequent Complete
    Sale, so performance reflects the realised hold period rather than
    extending past the exit."""

    # Look up subsequent Complete Sales per company from the FULL trade
    # history (not the filtered subset, which may exclude Complete Sales).
    cs = full_trades[full_trades["Transaction Type"] == "Complete Sale"]
    complete_sales_by_company: dict[str, list[pd.Timestamp]] = {
        name: sorted(grp["Earliest Trade Date"].tolist())
        for name, grp in cs.groupby("Instrument Name")
    }

    perfs, end_used = [], []
    for _, row in df.iterrows():
        name = row["Instrument Name"]
        trade_date = row["Earliest Trade Date"]

        if name not in prices.columns:
            perfs.append(np.nan); end_used.append(pd.NaT); continue
        series = prices[name]

        # Base end date per mode
        if mode == "Fixed days after trade":
            base_end = min(trade_date + pd.Timedelta(days=fixed_days),
                           prices.index.max())
        else:
            base_end = end_date

        # Cap Buys/Additions at the earliest subsequent Complete Sale of the
        # same name, if one exists.
        if row["Transaction Type"] in BUY_TYPES:
            future_cs = [d for d in complete_sales_by_company.get(name, [])
                         if d > trade_date]
            if future_cs:
                base_end = min(base_end, future_cs[0])

        sp = price_on_or_after(series, trade_date)
        ep = price_on_or_before(series, base_end)
        end_used.append(base_end)
        if sp and ep and sp > 0:
            perfs.append((ep / sp - 1) * 100)
        else:
            perfs.append(np.nan)
    return perfs, end_used


# -------------------------------------------------------------------
# Sidebar – filters
# -------------------------------------------------------------------
st.sidebar.title("🔍 Filters")

min_trade_date = trades["Earliest Trade Date"].min().date()
max_data_date = max(trades["Earliest Trade Date"].max().date(),
                    prices.index.max().date())

st.sidebar.markdown("**Trade Date Range**")
st.sidebar.caption("Only trades dated within this window will be plotted.")
date_selection = st.sidebar.date_input(
    "Select range",
    value=(min_trade_date, max_data_date),
    min_value=min_trade_date,
    max_value=max_data_date,
    label_visibility="collapsed",
)
if isinstance(date_selection, tuple) and len(date_selection) == 2:
    start_date, end_date = date_selection
else:
    start_date = date_selection if isinstance(date_selection, date) else min_trade_date
    end_date = max_data_date

st.sidebar.markdown("---")
st.sidebar.markdown("**Performance Window**")
st.sidebar.caption("How far forward from each trade to measure performance.")
perf_mode = st.sidebar.radio(
    "Measure performance until:",
    options=[
        "End of selected date range",
        "Latest available price",
        "Fixed days after trade",
    ],
    index=0,
    label_visibility="collapsed",
)
fixed_days = None
if perf_mode == "Fixed days after trade":
    fixed_days = st.sidebar.number_input(
        "Days after trade", min_value=1, max_value=3650, value=365, step=30
    )

st.sidebar.markdown("---")
all_types = sorted(trades["Transaction Type"].unique().tolist())
selected_types = st.sidebar.multiselect(
    "Transaction Type", options=all_types, default=all_types,
)

st.sidebar.markdown("---")
log_y = st.sidebar.checkbox(
    "Symmetric-log Y axis", value=False,
    help="Helpful when a few outliers compress the rest of the chart.",
)
clip_outliers = st.sidebar.checkbox(
    "Clip extreme outliers to ±500%", value=False,
    help="Caps performance below -100% or above +500% so the bulk is easier to read.",
)
floor_y_at_neg100 = st.sidebar.checkbox(
    "Cap Y axis at ±100%", value=False,
    help="A stock can only drop 100% from where you bought it. With this on, the "
         "Y axis is fixed at ±100% (symmetric quadrants) so downside detail is "
         "visible. Trades outside that range are clipped to the chart edge — "
         "the hover still shows their true performance.",
)

# -------------------------------------------------------------------
# Header
# -------------------------------------------------------------------
st.title("📊 LTGG Trade Performance Dashboard")

if perf_mode == "End of selected date range":
    sub = f"Performance measured from each trade date to **{end_date.strftime('%d %b %Y')}**."
elif perf_mode == "Latest available price":
    sub = f"Performance measured from each trade date to **{prices.index.max().strftime('%d %b %Y')}** (latest available)."
else:
    sub = f"Performance measured **{fixed_days} days** after each trade."
st.markdown(sub)

# -------------------------------------------------------------------
# Company search + dropdown (main panel, prominent)
# -------------------------------------------------------------------
all_companies = sorted(trades["Instrument Name"].unique().tolist())
current_portfolio_names = set(data.get("current_portfolio_names", []))
n_current = data.get("n_current_holdings", 0)

# Toggle: restrict to current holdings only
if current_portfolio_names:
    current_only = st.toggle(
        f"📌 Current portfolio only ({n_current} holdings)",
        value=False,
        help="Show only companies currently held in the LTGG portfolio. "
             f"{len(current_portfolio_names)} of {n_current} holdings have trade history; "
             "any held but never-traded names are excluded as there's nothing to plot for them.",
    )
else:
    current_only = False

available_companies = (
    sorted(c for c in all_companies if c in current_portfolio_names)
    if current_only else all_companies
)

c_search, c_pick = st.columns([1, 2])
with c_search:
    company_search = st.text_input(
        "🔍 Search companies",
        placeholder="e.g. Tesla, Alibaba…",
    )
with c_pick:
    if company_search:
        matching = [c for c in available_companies if company_search.lower() in c.lower()]
    else:
        matching = available_companies
    selected_companies = st.multiselect(
        f"Companies on chart ({len(matching)} match{'es' if len(matching) != 1 else ''})",
        options=matching,
        default=matching,
        placeholder="Pick one or more, or leave to show all matches",
    )

# -------------------------------------------------------------------
# Apply filters & compute performance
# -------------------------------------------------------------------
mask = (
    (trades["Earliest Trade Date"].dt.date >= start_date)
    & (trades["Earliest Trade Date"].dt.date <= end_date)
    & (trades["Transaction Type"].isin(selected_types))
    & (trades["Instrument Name"].isin(selected_companies))
)
filtered = trades.loc[mask].copy()

if perf_mode == "End of selected date range":
    endpoint = pd.Timestamp(end_date)
elif perf_mode == "Latest available price":
    endpoint = prices.index.max()
else:
    endpoint = None

perfs, end_used = compute_performance(filtered, trades, prices, perf_mode, endpoint, fixed_days)
filtered["Performance %"] = perfs
filtered["Measured Until"] = end_used
plot_data = filtered.dropna(subset=["Performance %"]).copy()

if floor_y_at_neg100:
    # Cap performance at ±100% so the symmetric chart has visible downside.
    plot_data["Performance % (plot)"] = plot_data["Performance %"].clip(-100, 100)
elif clip_outliers:
    plot_data["Performance % (plot)"] = plot_data["Performance %"].clip(-100, 500)
else:
    plot_data["Performance % (plot)"] = plot_data["Performance %"]

# Signed trade weight: sales become negative so the chart forms 4 quadrants
SALE_TYPES = {"Partial Sale", "Complete Sale"}
plot_data["Signed Weight"] = np.where(
    plot_data["Transaction Type"].isin(SALE_TYPES),
    -plot_data["% Portfolio Order"],
    plot_data["% Portfolio Order"],
)

# Pre-formatted performance string for hover (plotly's :.0f format spec
# is unreliable; rendering a finished string sidesteps it entirely)
plot_data["Perf Display"] = plot_data["Performance %"].apply(lambda x: f"{x:+.0f}%")

# -------------------------------------------------------------------
# KPIs – split into Buys vs Sales so averages are comparable
# -------------------------------------------------------------------
buy_data = plot_data[~plot_data["Transaction Type"].isin(SALE_TYPES)]
sale_data = plot_data[plot_data["Transaction Type"].isin(SALE_TYPES)]

def _kpi_row(df: pd.DataFrame, label: str, n_total: int, is_sales: bool = False):
    st.markdown(f"**{label}** — {n_total} trade{'s' if n_total != 1 else ''}")
    c1, c2, c3, c4, c5 = st.columns(5)
    if len(df):
        c1.metric("Mean", f"{df['Performance %'].mean():+.0f}%")
        c2.metric("Median", f"{df['Performance %'].median():+.0f}%")
        c3.metric("% positive", f"{(df['Performance %'] > 0).mean()*100:.0f}%")
        # For sales, "best" means biggest avoided loss (most negative perf
        # after sale) and "worst" means biggest miss (most positive perf
        # after sale, i.e. sold something that kept rising).
        if is_sales:
            c4.metric("Best", f"{df['Performance %'].min():+.0f}%",
                      help="Biggest drop after the sale – your best-timed exit.")
            c5.metric("Worst", f"{df['Performance %'].max():+.0f}%",
                      help="Biggest rise after the sale – left the most on the table.")
        else:
            c4.metric("Best", f"{df['Performance %'].max():+.0f}%")
            c5.metric("Worst", f"{df['Performance %'].min():+.0f}%")
    else:
        for c in (c1, c2, c3, c4, c5):
            c.metric("—", "—")

_kpi_row(buy_data, "🟢 Buys (New Buy + Addition)", len(buy_data))
_kpi_row(sale_data, "🔴 Sales (Partial + Complete)", len(sale_data), is_sales=True)

# -------------------------------------------------------------------
# Scatter plot
# -------------------------------------------------------------------
COLOR_MAP = {
    "New Buy":       "#2ca02c",
    "Addition":      "#1f77b4",
    "Partial Sale":  "#ff7f0e",
    "Complete Sale": "#d62728",
}

if len(plot_data) == 0:
    st.warning("No trades match the current filters.")
else:
    fig = px.scatter(
        plot_data,
        x="Signed Weight",
        y="Performance % (plot)",
        color="Transaction Type",
        color_discrete_map=COLOR_MAP,
        category_orders={"Transaction Type": ["New Buy", "Addition", "Partial Sale", "Complete Sale"]},
        custom_data=["Instrument Name", "Earliest Trade Date",
                     "Transaction Type", "% Portfolio Order", "Perf Display"],
    )
    fig.update_traces(
        marker=dict(size=11, opacity=0.78,
                    line=dict(width=0.5, color="rgba(255,255,255,0.6)")),
        hovertemplate=(
            "<b>%{customdata[0]}</b><br>"
            "Date: %{customdata[1]|%d %b %Y}<br>"
            "Type: %{customdata[2]}<br>"
            "Trade weight: %{customdata[3]:.2f}%<br>"
            "Performance: %{customdata[4]}"
            "<extra></extra>"
        ),
    )
    # Quadrant guide lines
    fig.add_hline(y=0, line_dash="dash", line_color="grey", opacity=0.5)
    fig.add_vline(x=0, line_dash="dash", line_color="grey", opacity=0.5)

    # Subtle quadrant labels (paper coordinates so they sit in the corners)
    quadrant_font = dict(size=11, color="rgba(120,120,120,0.7)")
    fig.add_annotation(xref="paper", yref="paper", x=0.99, y=0.98,
                       text="Good buys<br>(bought, went up)",
                       showarrow=False, align="right",
                       font=quadrant_font, xanchor="right", yanchor="top")
    fig.add_annotation(xref="paper", yref="paper", x=0.99, y=0.02,
                       text="Poor buys<br>(bought, went down)",
                       showarrow=False, align="right",
                       font=quadrant_font, xanchor="right", yanchor="bottom")
    fig.add_annotation(xref="paper", yref="paper", x=0.01, y=0.98,
                       text="Premature sales<br>(sold, kept rising)",
                       showarrow=False, align="left",
                       font=quadrant_font, xanchor="left", yanchor="top")
    fig.add_annotation(xref="paper", yref="paper", x=0.01, y=0.02,
                       text="Avoided losses<br>(sold, then dropped)",
                       showarrow=False, align="left",
                       font=quadrant_font, xanchor="left", yanchor="bottom")

    fig.update_layout(
        height=620,
        hovermode="closest",
        xaxis_title="Trade weight (% of portfolio) — buys positive, sales negative",
        yaxis_title="Performance (%)" + (
            " – capped ±100%" if floor_y_at_neg100
            else " – clipped" if clip_outliers else ""
        ),
        yaxis=dict(tickformat=".0f", hoverformat=".0f"),
        xaxis=dict(tickformat=".2f", hoverformat=".2f"),
        legend=dict(orientation="h", yanchor="bottom", y=1.02,
                    xanchor="right", x=1, title=None),
        margin=dict(l=10, r=10, t=40, b=10),
        plot_bgcolor="rgba(0,0,0,0)",
    )
    fig.update_xaxes(showgrid=True, gridcolor="rgba(128,128,128,0.18)", zeroline=False)
    fig.update_yaxes(showgrid=True, gridcolor="rgba(128,128,128,0.18)", zeroline=False)

    if log_y:
        fig.update_yaxes(type="log")
    else:
        # Force symmetric axes by adding invisible anchor points at the
        # four corners.  Plotly autorange then naturally produces ±max.
        # This is more reliable than setting range= which the JS renderer
        # can override on first draw.
        x_abs = float(plot_data["Signed Weight"].abs().max() or 0) * 1.08
        y_abs = float(plot_data["Performance % (plot)"].abs().max() or 0) * 1.08
        if x_abs == 0: x_abs = 1
        if y_abs == 0: y_abs = 1

        # Decide Y-axis bounds. Default = symmetric around 0 sized to data.
        # With the "Cap Y axis at ±100%" toggle, the box is symmetric and
        # fixed at ±100 so downside detail is preserved (clipped values
        # already sit at the boundary thanks to the plot-data clip above).
        if floor_y_at_neg100:
            y_min, y_max = -100.0, 100.0
        else:
            y_min = -y_abs
            y_max = y_abs

        fig.add_trace(go.Scatter(
            x=[-x_abs, x_abs, -x_abs, x_abs],
            y=[y_min, y_min, y_max, y_max],
            mode="markers",
            marker=dict(size=0.1, opacity=0),
            hoverinfo="skip",
            showlegend=False,
        ))

    st.plotly_chart(fig, use_container_width=True)

# -------------------------------------------------------------------
# Breakdown by transaction type
# -------------------------------------------------------------------
if len(plot_data):
    st.subheader("Breakdown by transaction type")
    summary = (
        plot_data.groupby("Transaction Type")["Performance %"]
        .agg(["count", "mean", "median", "min", "max"])
        .rename(columns={"count": "Trades", "mean": "Mean %",
                         "median": "Median %", "min": "Min %", "max": "Max %"})
        .reindex(["New Buy", "Addition", "Partial Sale", "Complete Sale"])
        .dropna(how="all")
    )
    summary[["Mean %", "Median %", "Min %", "Max %"]] = (
        summary[["Mean %", "Median %", "Min %", "Max %"]].round(1)
    )
    st.dataframe(summary, use_container_width=True)

# -------------------------------------------------------------------
# Underlying data table
# -------------------------------------------------------------------
with st.expander("📋 View underlying trade data"):
    if len(plot_data):
        show = plot_data[[
            "Earliest Trade Date", "Instrument Name", "Transaction Type",
            "% Portfolio Order", "Performance %"
        ]].copy()
        show["Earliest Trade Date"] = show["Earliest Trade Date"].dt.strftime("%Y-%m-%d")
        show["% Portfolio Order"] = show["% Portfolio Order"].round(2)
        show["Performance %"] = show["Performance %"].round(0)
        show = show.sort_values("Earliest Trade Date", ascending=False).reset_index(drop=True)
        st.dataframe(show, use_container_width=True, height=400)

        st.download_button(
            "Download filtered data as CSV",
            show.to_csv(index=False).encode("utf-8"),
            file_name="ltgg_trade_performance.csv",
            mime="text/csv",
        )
    else:
        st.info("No trades match the current filters.")

# -------------------------------------------------------------------
# Footer – data freshness indicator
# -------------------------------------------------------------------
st.markdown("---")
gen = data.get("generated_at_utc")
if isinstance(gen, datetime):
    if gen.tzinfo is None:
        gen = gen.replace(tzinfo=timezone.utc)
    age_days = (datetime.now(timezone.utc) - gen).days
    age_txt = "today" if age_days == 0 else f"{age_days} day{'s' if age_days != 1 else ''} ago"
    src = data.get("source_filename", "—")
    last_price_dt = data.get("price_date_range", (None, None))[1]
    last_price_str = last_price_dt.strftime("%d %b %Y") if last_price_dt else "—"
    st.caption(
        f"📦 Data refreshed **{age_txt}** ({gen.strftime('%Y-%m-%d %H:%M UTC')}) "
        f"from `{src}`. "
        f"{data.get('n_trades', '?')} trades · {data.get('n_companies', '?')} companies · "
        f"prices to {last_price_str}."
    )
st.caption(
    "Performance uses each company's total-return index (dividends and "
    "corporate actions included). For New Buys and Additions, performance is "
    "capped at the subsequent Complete Sale of the same name (if any), so it "
    "reflects the realised hold period rather than extending past the exit. "
    "Alibaba (HK Line) trades use the Alibaba ADR series as a proxy."
)
