"""
LTGG Trade Performance Dashboard
Reads pre-processed data from data.pkl (generated by build_data_pkl.py / the Colab notebook).
"""

from __future__ import annotations

import pickle
from datetime import date, datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# -------------------------------------------------------------------
# Page config
# -------------------------------------------------------------------
st.set_page_config(
    page_title="LTGG Trade Performance",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
)

PKL_PATH = "data.pkl"

# -------------------------------------------------------------------
# Data loading (cached, auto-invalidates when the pickle file changes)
# -------------------------------------------------------------------
@st.cache_data(show_spinner="Loading data…")
def load_data(pkl_path: str = PKL_PATH, _mtime: float | None = None):
    """`_mtime` is part of the cache key, so the cache is invalidated
    automatically whenever data.pkl is replaced."""
    with open(pkl_path, "rb") as f:
        return pickle.load(f)


def _pkl_mtime(pkl_path: str = PKL_PATH) -> float:
    p = Path(pkl_path)
    return p.stat().st_mtime if p.exists() else 0.0


if not Path(PKL_PATH).exists():
    st.error(
        f"`{PKL_PATH}` not found. Generate it with **build_data_pkl.py** "
        "(or run **build_data_pkl.ipynb** in Colab) and place it next to `app.py`."
    )
    st.stop()

data = load_data(PKL_PATH, _mtime=_pkl_mtime(PKL_PATH))
trades: pd.DataFrame = data["trades"]
prices: pd.DataFrame = data["prices"]

# -------------------------------------------------------------------
# Helpers
# -------------------------------------------------------------------
def price_on_or_after(series: pd.Series, dt: pd.Timestamp):
    s = series.dropna()
    v = s[s.index >= dt]
    return float(v.iloc[0]) if len(v) else None


def price_on_or_before(series: pd.Series, dt: pd.Timestamp):
    s = series.dropna()
    v = s[s.index <= dt]
    return float(v.iloc[-1]) if len(v) else None


def compute_performance(df: pd.DataFrame, prices: pd.DataFrame, mode: str,
                        end_date: pd.Timestamp | None, fixed_days: int | None):
    perfs, end_used = [], []
    for _, row in df.iterrows():
        name = row["Instrument Name"]
        if name not in prices.columns:
            perfs.append(np.nan); end_used.append(pd.NaT); continue
        series = prices[name]
        sp = price_on_or_after(series, row["Earliest Trade Date"])
        if mode == "Fixed days after trade":
            target = row["Earliest Trade Date"] + pd.Timedelta(days=fixed_days)
            target = min(target, prices.index.max())
            ep = price_on_or_before(series, target)
            end_used.append(target)
        else:
            ep = price_on_or_before(series, end_date)
            end_used.append(end_date)
        if sp and ep and sp > 0:
            perfs.append((ep / sp - 1) * 100)
        else:
            perfs.append(np.nan)
    return perfs, end_used


# -------------------------------------------------------------------
# Sidebar – filters
# -------------------------------------------------------------------
st.sidebar.title("🔍 Filters")

min_trade_date = trades["Earliest Trade Date"].min().date()
max_data_date = max(trades["Earliest Trade Date"].max().date(),
                    prices.index.max().date())

st.sidebar.markdown("**Trade Date Range**")
st.sidebar.caption("Only trades dated within this window will be plotted.")
date_selection = st.sidebar.date_input(
    "Select range",
    value=(min_trade_date, max_data_date),
    min_value=min_trade_date,
    max_value=max_data_date,
    label_visibility="collapsed",
)
if isinstance(date_selection, tuple) and len(date_selection) == 2:
    start_date, end_date = date_selection
else:
    start_date = date_selection if isinstance(date_selection, date) else min_trade_date
    end_date = max_data_date

st.sidebar.markdown("---")
st.sidebar.markdown("**Performance Window**")
st.sidebar.caption("How far forward from each trade to measure performance.")
perf_mode = st.sidebar.radio(
    "Measure performance until:",
    options=[
        "End of selected date range",
        "Latest available price",
        "Fixed days after trade",
    ],
    index=0,
    label_visibility="collapsed",
)
fixed_days = None
if perf_mode == "Fixed days after trade":
    fixed_days = st.sidebar.number_input(
        "Days after trade", min_value=1, max_value=3650, value=365, step=30
    )

st.sidebar.markdown("---")
all_types = sorted(trades["Transaction Type"].unique().tolist())
selected_types = st.sidebar.multiselect(
    "Transaction Type", options=all_types, default=all_types,
)

st.sidebar.markdown("---")
log_y = st.sidebar.checkbox(
    "Symmetric-log Y axis", value=False,
    help="Helpful when a few outliers compress the rest of the chart.",
)
clip_outliers = st.sidebar.checkbox(
    "Clip extreme outliers to ±500%", value=False,
    help="Caps performance below -100% or above +500% so the bulk is easier to read.",
)

# -------------------------------------------------------------------
# Header
# -------------------------------------------------------------------
st.title("📊 LTGG Trade Performance Dashboard")

if perf_mode == "End of selected date range":
    sub = f"Performance measured from each trade date to **{end_date.strftime('%d %b %Y')}**."
elif perf_mode == "Latest available price":
    sub = f"Performance measured from each trade date to **{prices.index.max().strftime('%d %b %Y')}** (latest available)."
else:
    sub = f"Performance measured **{fixed_days} days** after each trade."
st.markdown(sub)

# -------------------------------------------------------------------
# Company search + dropdown (main panel, prominent)
# -------------------------------------------------------------------
all_companies = sorted(trades["Instrument Name"].unique().tolist())

c_search, c_pick = st.columns([1, 2])
with c_search:
    company_search = st.text_input(
        "🔍 Search companies",
        placeholder="e.g. Tesla, Alibaba…",
    )
with c_pick:
    if company_search:
        matching = [c for c in all_companies if company_search.lower() in c.lower()]
    else:
        matching = all_companies
    selected_companies = st.multiselect(
        f"Companies on chart ({len(matching)} match{'es' if len(matching) != 1 else ''})",
        options=matching,
        default=matching,
        placeholder="Pick one or more, or leave to show all matches",
    )

# -------------------------------------------------------------------
# Apply filters & compute performance
# -------------------------------------------------------------------
mask = (
    (trades["Earliest Trade Date"].dt.date >= start_date)
    & (trades["Earliest Trade Date"].dt.date <= end_date)
    & (trades["Transaction Type"].isin(selected_types))
    & (trades["Instrument Name"].isin(selected_companies))
)
filtered = trades.loc[mask].copy()

if perf_mode == "End of selected date range":
    endpoint = pd.Timestamp(end_date)
elif perf_mode == "Latest available price":
    endpoint = prices.index.max()
else:
    endpoint = None

perfs, end_used = compute_performance(filtered, prices, perf_mode, endpoint, fixed_days)
filtered["Performance %"] = perfs
filtered["Measured Until"] = end_used
plot_data = filtered.dropna(subset=["Performance %"]).copy()

plot_data["Performance % (plot)"] = (
    plot_data["Performance %"].clip(-100, 500) if clip_outliers else plot_data["Performance %"]
)

# Signed trade weight: sales become negative so the chart forms 4 quadrants
SALE_TYPES = {"Partial Sale", "Complete Sale"}
plot_data["Signed Weight"] = np.where(
    plot_data["Transaction Type"].isin(SALE_TYPES),
    -plot_data["% Portfolio Order"],
    plot_data["% Portfolio Order"],
)

# -------------------------------------------------------------------
# KPIs
# -------------------------------------------------------------------
k1, k2, k3, k4, k5 = st.columns(5)
k1.metric("Trades shown", f"{len(plot_data):,}")
if len(plot_data):
    k2.metric("Mean", f"{plot_data['Performance %'].mean():+.1f}%")
    k3.metric("Median", f"{plot_data['Performance %'].median():+.1f}%")
    k4.metric("% positive", f"{(plot_data['Performance %'] > 0).mean()*100:.0f}%")
    k5.metric("Best / worst",
              f"{plot_data['Performance %'].max():+.0f}% / {plot_data['Performance %'].min():+.0f}%")
else:
    for k in (k2, k3, k4, k5):
        k.metric("—", "—")

# -------------------------------------------------------------------
# Scatter plot
# -------------------------------------------------------------------
COLOR_MAP = {
    "New Buy":       "#2ca02c",
    "Addition":      "#1f77b4",
    "Partial Sale":  "#ff7f0e",
    "Complete Sale": "#d62728",
}

if len(plot_data) == 0:
    st.warning("No trades match the current filters.")
else:
    fig = px.scatter(
        plot_data,
        x="Signed Weight",
        y="Performance % (plot)",
        color="Transaction Type",
        color_discrete_map=COLOR_MAP,
        category_orders={"Transaction Type": ["New Buy", "Addition", "Partial Sale", "Complete Sale"]},
        custom_data=["Instrument Name", "Earliest Trade Date",
                     "Transaction Type", "% Portfolio Order", "Performance %"],
    )
    fig.update_traces(
        marker=dict(size=11, opacity=0.78,
                    line=dict(width=0.5, color="rgba(255,255,255,0.6)")),
        hovertemplate=(
            "<b>%{customdata[0]}</b><br>"
            "Date: %{customdata[1]|%d %b %Y}<br>"
            "Type: %{customdata[2]}<br>"
            "Trade weight: %{customdata[3]:.2f}%<br>"
            "Performance: %{customdata[4]:+.0f}%"
            "<extra></extra>"
        ),
    )
    # Quadrant guide lines
    fig.add_hline(y=0, line_dash="dash", line_color="grey", opacity=0.5)
    fig.add_vline(x=0, line_dash="dash", line_color="grey", opacity=0.5)

    # Subtle quadrant labels (paper coordinates so they sit in the corners)
    quadrant_font = dict(size=11, color="rgba(120,120,120,0.7)")
    fig.add_annotation(xref="paper", yref="paper", x=0.99, y=0.98,
                       text="Good buys<br>(bought, went up)",
                       showarrow=False, align="right",
                       font=quadrant_font, xanchor="right", yanchor="top")
    fig.add_annotation(xref="paper", yref="paper", x=0.99, y=0.02,
                       text="Poor buys<br>(bought, went down)",
                       showarrow=False, align="right",
                       font=quadrant_font, xanchor="right", yanchor="bottom")
    fig.add_annotation(xref="paper", yref="paper", x=0.01, y=0.98,
                       text="Premature sales<br>(sold, kept rising)",
                       showarrow=False, align="left",
                       font=quadrant_font, xanchor="left", yanchor="top")
    fig.add_annotation(xref="paper", yref="paper", x=0.01, y=0.02,
                       text="Avoided losses<br>(sold, then dropped)",
                       showarrow=False, align="left",
                       font=quadrant_font, xanchor="left", yanchor="bottom")

    fig.update_layout(
        height=620,
        hovermode="closest",
        xaxis_title="Trade weight (% of portfolio) — buys positive, sales negative",
        yaxis_title="Performance (%)" + (" – clipped" if clip_outliers else ""),
        legend=dict(orientation="h", yanchor="bottom", y=1.02,
                    xanchor="right", x=1, title=None),
        margin=dict(l=10, r=10, t=40, b=10),
        plot_bgcolor="rgba(0,0,0,0)",
    )
    fig.update_xaxes(showgrid=True, gridcolor="rgba(128,128,128,0.18)", zeroline=False)
    fig.update_yaxes(showgrid=True, gridcolor="rgba(128,128,128,0.18)", zeroline=False)

    if log_y:
        fig.update_yaxes(type="log")
    else:
        # Force symmetric axes by adding invisible anchor points at the
        # four corners.  Plotly autorange then naturally produces ±max.
        # This is more reliable than setting range= which the JS renderer
        # can override on first draw.
        x_abs = float(plot_data["Signed Weight"].abs().max() or 0) * 1.08
        y_abs = float(plot_data["Performance % (plot)"].abs().max() or 0) * 1.08
        if x_abs == 0: x_abs = 1
        if y_abs == 0: y_abs = 1

        fig.add_trace(go.Scatter(
            x=[-x_abs, x_abs, -x_abs, x_abs],
            y=[-y_abs, -y_abs, y_abs, y_abs],
            mode="markers",
            marker=dict(size=0.1, opacity=0),
            hoverinfo="skip",
            showlegend=False,
        ))

    st.plotly_chart(fig, use_container_width=True)

# -------------------------------------------------------------------
# Breakdown by transaction type
# -------------------------------------------------------------------
if len(plot_data):
    st.subheader("Breakdown by transaction type")
    summary = (
        plot_data.groupby("Transaction Type")["Performance %"]
        .agg(["count", "mean", "median", "min", "max"])
        .rename(columns={"count": "Trades", "mean": "Mean %",
                         "median": "Median %", "min": "Min %", "max": "Max %"})
        .reindex(["New Buy", "Addition", "Partial Sale", "Complete Sale"])
        .dropna(how="all")
    )
    summary[["Mean %", "Median %", "Min %", "Max %"]] = (
        summary[["Mean %", "Median %", "Min %", "Max %"]].round(1)
    )
    st.dataframe(summary, use_container_width=True)

# -------------------------------------------------------------------
# Underlying data table
# -------------------------------------------------------------------
with st.expander("📋 View underlying trade data"):
    if len(plot_data):
        show = plot_data[[
            "Earliest Trade Date", "Instrument Name", "Transaction Type",
            "% Portfolio Order", "Performance %"
        ]].copy()
        show["Earliest Trade Date"] = show["Earliest Trade Date"].dt.strftime("%Y-%m-%d")
        show["% Portfolio Order"] = show["% Portfolio Order"].round(2)
        show["Performance %"] = show["Performance %"].round(0)
        show = show.sort_values("Earliest Trade Date", ascending=False).reset_index(drop=True)
        st.dataframe(show, use_container_width=True, height=400)

        st.download_button(
            "Download filtered data as CSV",
            show.to_csv(index=False).encode("utf-8"),
            file_name="ltgg_trade_performance.csv",
            mime="text/csv",
        )
    else:
        st.info("No trades match the current filters.")

# -------------------------------------------------------------------
# Footer – data freshness indicator
# -------------------------------------------------------------------
st.markdown("---")
gen = data.get("generated_at_utc")
if isinstance(gen, datetime):
    if gen.tzinfo is None:
        gen = gen.replace(tzinfo=timezone.utc)
    age_days = (datetime.now(timezone.utc) - gen).days
    age_txt = "today" if age_days == 0 else f"{age_days} day{'s' if age_days != 1 else ''} ago"
    src = data.get("source_filename", "—")
    last_price_dt = data.get("price_date_range", (None, None))[1]
    last_price_str = last_price_dt.strftime("%d %b %Y") if last_price_dt else "—"
    st.caption(
        f"📦 Data refreshed **{age_txt}** ({gen.strftime('%Y-%m-%d %H:%M UTC')}) "
        f"from `{src}`. "
        f"{data.get('n_trades', '?')} trades · {data.get('n_companies', '?')} companies · "
        f"prices to {last_price_str}."
    )
st.caption(
    "Performance uses each company's total-return index (dividends and corporate actions included). "
    "Alibaba (HK Line) trades use the Alibaba ADR series as a proxy."
)
